<a href="https://colab.research.google.com/github/arun9718/Data-Science---Learning/blob/Day2/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4])

In [3]:
print(type(arr))

<class 'numpy.ndarray'>


In [4]:
print(arr.ndim)

1


In [5]:
arr.dtype

dtype('int64')

In [6]:
arr1=np.array([1,2,3,4,5],dtype='uint8')

In [7]:
arr1

array([1, 2, 3, 4, 5], dtype=uint8)

## Time Diff of numpy array and normal python list

In [8]:
lst= [1] * 1000000

In [9]:
print(lst)
print(type(lst))

%timeit sum(lst)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



100 loops, best of 5: 7.49 ms per loop


In [11]:
arr= np.ones(1000000,dtype='uint8')

%timeit arr.sum()

The slowest run took 5.06 times longer than the fastest. This could mean that an intermediate result is being cached.
1000 loops, best of 5: 1.11 ms per loop


**Numpy stands for Numerical Python
It is a library in python to work with arrays
We can clearly see the diff between the two operations this is because numpy on the backend is implemented in C++ so the array elements is stored as contiguos elements
Another reason for the numpy array to be fast is that in list the list stores the addresses of the elements while the elements are stored in some other places in the memory But in numpy array the elements are itself stored in the array Hence it is fast**

In [12]:
arr=arr*1000

In [13]:
print(arr)

[1000 1000 1000 ... 1000 1000 1000]


## Slicing in Numpy

In [14]:
arr=np.arange(5,50,5)

In [15]:
print(arr)

[ 5 10 15 20 25 30 35 40 45]


In [16]:
## Diff of slicing in numpy and python is that in python list everytime we slice a new copy is made while in numpy array 
##only a view of the numpy array is shown

In [17]:
list1=[1,2,3,4,5]
list2=list1[2:5]
print(list1)
print(list2)
list2[0]=100
print(list1)
print(list2)

[1, 2, 3, 4, 5]
[3, 4, 5]
[1, 2, 3, 4, 5]
[100, 4, 5]


## We can see that the original list is not affected

In [19]:
arr1=np.array([1,2,3,4,5])
arr2=arr1[2:5]
print(arr1)
print(arr2)
arr2[0]=100
print(arr1)
print(arr2)

[1 2 3 4 5]
[3 4 5]
[  1   2 100   4   5]
[100   4   5]


## We can see that the original array is affected as the new slcing only just a view of the original array

In [20]:
arr1=np.array([1,2,3,4,5])
arr2=arr1[2:5].copy()
print(arr1)
print(arr2)
arr2[0]=100
print(arr1)
print(arr2)

[1 2 3 4 5]
[3 4 5]
[1 2 3 4 5]
[100   4   5]


## Now we made a copy() purposely