<a href="https://colab.research.google.com/github/arun9718/Data-Science---Learning/blob/Day2/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4])

In [3]:
print(type(arr))

<class 'numpy.ndarray'>


In [4]:
print(arr.ndim)

1


In [5]:
arr.dtype

dtype('int64')

In [6]:
arr1=np.array([1,2,3,4,5],dtype='uint8')

In [7]:
arr1

array([1, 2, 3, 4, 5], dtype=uint8)

## Time Diff of numpy array and normal python list

In [8]:
lst= [1] * 1000000

In [9]:
print(lst)
print(type(lst))

%timeit sum(lst)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



100 loops, best of 5: 7.49 ms per loop


In [11]:
arr= np.ones(1000000,dtype='uint8')

%timeit arr.sum()

The slowest run took 5.06 times longer than the fastest. This could mean that an intermediate result is being cached.
1000 loops, best of 5: 1.11 ms per loop


**Numpy stands for Numerical Python
It is a library in python to work with arrays
We can clearly see the diff between the two operations this is because numpy on the backend is implemented in C++ so the array elements is stored as contiguos elements
Another reason for the numpy array to be fast is that in list the list stores the addresses of the elements while the elements are stored in some other places in the memory But in numpy array the elements are itself stored in the array Hence it is fast**

In [12]:
arr=arr*1000

In [13]:
print(arr)

[1000 1000 1000 ... 1000 1000 1000]


## Slicing in Numpy

In [14]:
arr=np.arange(5,50,5)

In [15]:
print(arr)

[ 5 10 15 20 25 30 35 40 45]


In [16]:
## Diff of slicing in numpy and python is that in python list everytime we slice a new copy is made while in numpy array 
##only a view of the numpy array is shown

In [17]:
list1=[1,2,3,4,5]
list2=list1[2:5]
print(list1)
print(list2)
list2[0]=100
print(list1)
print(list2)

[1, 2, 3, 4, 5]
[3, 4, 5]
[1, 2, 3, 4, 5]
[100, 4, 5]


## We can see that the original list is not affected

In [19]:
arr1=np.array([1,2,3,4,5])
arr2=arr1[2:5]
print(arr1)
print(arr2)
arr2[0]=100
print(arr1)
print(arr2)

[1 2 3 4 5]
[3 4 5]
[  1   2 100   4   5]
[100   4   5]


## We can see that the original array is affected as the new slcing only just a view of the original array

In [20]:
arr1=np.array([1,2,3,4,5])
arr2=arr1[2:5].copy()
print(arr1)
print(arr2)
arr2[0]=100
print(arr1)
print(arr2)

[1 2 3 4 5]
[3 4 5]
[1 2 3 4 5]
[100   4   5]


## Now we made a copy() purposely

## 2D Array

In [21]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [22]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
arr1=arr[-1::-1,-1::-1]
print(arr1)

[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [27]:
arr.ndim

2

In [28]:
arr.shape

(3, 3)

In [29]:
arr.size

9

In [30]:
arr[0][1]

2

In [31]:
arr[0,1]

2

In [32]:
#We can create an array of ones of any dimension
aar2=np.ones((2,3,4,5))

In [33]:
aar2

array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]])

In [34]:
#We can see a 4d array above

## Some more functions in numpy

In [35]:
ar=np.arange(2,30,3)

In [36]:
ar

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29])

In [38]:
np.random.permutation(ar) #It randomly arranges the given numpy array

array([11,  5, 14, 23, 17,  2, 20, 29, 26,  8])

In [43]:
np.random.randint(1,20)

1

In [44]:
#now we are going to use a random funtion which in back uses gaussian distribution to store the array

In [46]:
a=np.random.randn(100)

In [47]:
print(a.mean(),a.std())

0.07764710730933574 1.0507494816923846


In [48]:
#Since it follow normal/gaussian distribution the mean will always be around 0 and the stadard deviation will always be around 1

In [49]:
#We have another function linspace which gives an array of numbers between two intervals which are equally spaced and number of numbers in between the interval can be explicitly mentioned

In [50]:
linarr=np.linspace(1,5,100)

In [53]:
#Now we can check be checking the diff between two consecutive elements
print(linarr[10]-linarr[9])
print(linarr[20]-linarr[19])

#We can see the diff is moreover same

0.04040404040404022
0.04040404040404044


In [ ]:
#We have where() function and reshape function
#Where() funciton is like if else applied inside the numpy array