<a href="https://colab.research.google.com/github/arun9718/Data-Science---Learning/blob/Day3/Pandas/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

## Series

In [ ]:
A = pd.Series([10,20,33,44])

In [ ]:
A

0    10
1    20
2    33
3    44
dtype: int64

In [ ]:
print(A.values)

[10 20 33 44]


In [ ]:
type(A)

pandas.core.series.Series

In [ ]:
type(A.values)

numpy.ndarray

In [ ]:
print(A.index)

RangeIndex(start=0, stop=4, step=1)


In [ ]:
print(type(A.index))

<class 'pandas.core.indexes.range.RangeIndex'>


In [ ]:
A = pd.Series([10,20,30,"40"],index = ['a','b','c','d'])

In [ ]:
A

a    10
b    20
c    30
d    40
dtype: object

In [ ]:
print(A.values)

[10 20 30 '40']


In [ ]:
arr = A.values

In [ ]:
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
print(type(arr[3]))

<class 'str'>


## Slicing

In [ ]:
A

a    10
b    20
c    30
d    40
dtype: object

In [ ]:
A['a':'c']

a    10
b    20
c    30
dtype: object

In [ ]:
A[0:2]

a    10
b    20
dtype: object

In [ ]:
#iloc implicit index
#loc explicit index



In [ ]:
A.iloc[0:2]

a    10
b    20
dtype: object

In [ ]:
A.loc['a':'c']

a    10
b    20
c    30
dtype: object

In [ ]:
# from Dictionary

In [ ]:
height_dict = {"A":10,"B":20,"C":30}

In [ ]:
height = pd.Series(height_dict)

In [ ]:
height

A    10
B    20
C    30
dtype: int64

In [ ]:
weight_dict = {'A':100,'B':110,'C':150}

In [ ]:
weight = pd.Series(weight_dict)

In [ ]:
weight

A    100
B    110
C    150
dtype: int64

## DataFrame

In [ ]:
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [ ]:
print(df.values)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(type(df.values))

<class 'numpy.ndarray'>


In [ ]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [ ]:
df.columns

RangeIndex(start=0, stop=3, step=1)

In [ ]:
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],index=["A","B","C"])

In [ ]:
df

0  1  2
A  1  2  3
B  4  5  6
C  7  8  9

In [ ]:
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],index=["A","B","C"],columns = ['c1','c2','c3'])

In [ ]:
df

c1  c2  c3
A   1   2   3
B   4   5   6
C   7   8   9

In [ ]:
height

A    10
B    20
C    30
dtype: int64

In [ ]:
weight

A    100
B    110
C    150
dtype: int64

In [ ]:
df = pd.DataFrame({'Height':height,'weight':weight})

In [ ]:
df

Height  weight
A      10     100
B      20     110
C      30     150

In [ ]:
print(df.index)

Index(['A', 'B', 'C'], dtype='object')


In [ ]:
print(df.columns)

Index(['Height', 'weight'], dtype='object')


In [ ]:
df

Height  weight
A      10     100
B      20     110
C      30     150

In [ ]:
df.loc['B':'C']

Height  weight
B      20     110
C      30     150

In [ ]:
df.iloc[1:3]

Height  weight
B      20     110
C      30     150

In [ ]:
df[['Height']]

Height
A      10
B      20
C      30

In [ ]:
df

Height  weight
A      10     100
B      20     110
C      30     150

In [ ]:
df[[True,False]]

ValueError: ignored

In [ ]:
df[df['Height']>15]

Height  weight
B      20     110
C      30     150

In [ ]:
df["Test"] = df['Height']*10

In [ ]:
df

In [ ]:
del df['Height']

In [ ]:
df

In [ ]:
df.drop(columns = ["Test"],index=['B'],inplace = True)

In [ ]:
df

weight
A     100
C     150

In [ ]:
df = pd.DataFrame({
    'Height': height,
    'Weight': weight,
})
df

Height  Weight
A      10     100
B      20     110
C      30     150

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, A to C
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Height  3 non-null      int64
 1   Weight  3 non-null      int64
dtypes: int64(2)
memory usage: 152.0+ bytes


In [ ]:
df.head()

Height  Weight
A      10     100
B      20     110
C      30     150

In [ ]:
df.head(1)

Height  Weight
A      10     100

In [ ]:
df.tail(2)

Height  Weight
B      20     110
C      30     150

In [ ]:
df.describe()

Height      Weight
count     3.0    3.000000
mean     20.0  120.000000
std      10.0   26.457513
min      10.0  100.000000
25%      15.0  105.000000
50%      20.0  110.000000
75%      25.0  130.000000
max      30.0  150.000000

## Missing Data

In [ ]:
dict1 = {'A': 48, 'C':69}
dict2 = {'B':5.8, 'C':6.2}
dict3 = {'A': 10, 'B':15, 'C':12}

In [ ]:
df = pd.DataFrame({"Height":dict1,"Weight":dict2,"Age":dict3})

In [ ]:
df

Height  Weight  Age
A    48.0     NaN   10
C    69.0     6.2   12
B     NaN     5.8   15

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, A to B
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Height  2 non-null      float64
 1   Weight  2 non-null      float64
 2   Age     3 non-null      int64  
dtypes: float64(2), int64(1)
memory usage: 96.0+ bytes


In [ ]:
df.dropna(axis=1)

Age
A   10
C   12
B   15

In [ ]:
df

Height  Weight  Age
A    48.0     NaN   10
C    69.0     6.2   12
B     NaN     5.8   15

In [ ]:
df['Height'].fillna(df['Height'].mean(),inplace=True)

In [ ]:
df

Height  Weight  Age
A    48.0     NaN   10
C    69.0     6.2   12
B    58.5     5.8   15

In [ ]:
A =df.loc['A']
print(A)
A.fillna(30, inplace = True)

Height    48.0
Weight     NaN
Age       10.0
Name: A, dtype: float64


/usr/local/lib/python3.7/dist-packages/pandas/core/series.py:4536: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,


In [ ]:
A

Height    48.0
Weight    30.0
Age       10.0
Name: A, dtype: float64

In [ ]:
#Update the Value of Weight of A
df

Height  Weight  Age
A    48.0     NaN   10
C    69.0     6.2   12
B    58.5     5.8   15

In [ ]:
df.loc['A'] = df.loc['A'].fillna(3)

In [ ]:
df

Height  Weight   Age
A    48.0     3.0  10.0
C    69.0     6.2  12.0
B    58.5     5.8  15.0

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/neylsoncrepalde/projeto_eda_covid/master/covid_19_data.csv")

In [ ]:
df.head()

SNo ObservationDate Province/State  ... Confirmed Deaths  Recovered
0    1      01/22/2020          Anhui  ...       1.0    0.0        0.0
1    2      01/22/2020        Beijing  ...      14.0    0.0        0.0
2    3      01/22/2020      Chongqing  ...       6.0    0.0        0.0
3    4      01/22/2020         Fujian  ...       1.0    0.0        0.0
4    5      01/22/2020          Gansu  ...       0.0    0.0        0.0

[5 rows x 8 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26713 entries, 0 to 26712
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   SNo              26713 non-null  int64  
 1   ObservationDate  26713 non-null  object 
 2   Province/State   12882 non-null  object 
 3   Country/Region   26713 non-null  object 
 4   Last Update      26713 non-null  object 
 5   Confirmed        26713 non-null  float64
 6   Deaths           26713 non-null  float64
 7   Recovered        26713 non-null  float64
dtypes: float64(3), int64(1), object(4)
memory usage: 1.6+ MB


In [ ]:
df.shape

(26713, 8)

In [ ]:
df.describe()

SNo      Confirmed        Deaths      Recovered
count  26713.000000   26713.000000  26713.000000   26713.000000
mean   13357.000000    5690.647550    373.353236    1736.979224
std     7711.523207   23417.369124   2214.074387   10864.727709
min        1.000000       0.000000      0.000000       0.000000
25%     6679.000000      18.000000      0.000000       0.000000
50%    13357.000000     192.000000      3.000000       8.000000
75%    20035.000000    1350.000000     28.000000     187.000000
max    26713.000000  352845.000000  35341.000000  289392.000000

In [ ]:
df

SNo ObservationDate Province/State  ... Confirmed Deaths  Recovered
0          1      01/22/2020          Anhui  ...       1.0    0.0        0.0
1          2      01/22/2020        Beijing  ...      14.0    0.0        0.0
2          3      01/22/2020      Chongqing  ...       6.0    0.0        0.0
3          4      01/22/2020         Fujian  ...       1.0    0.0        0.0
4          5      01/22/2020          Gansu  ...       0.0    0.0        0.0
...      ...             ...            ...  ...       ...    ...        ...
26708  26709      05/19/2020        Wyoming  ...     776.0   10.0        0.0
26709  26710      05/19/2020       Xinjiang  ...      76.0    3.0       73.0
26710  26711      05/19/2020          Yukon  ...      11.0    0.0       11.0
26711  26712      05/19/2020         Yunnan  ...     185.0    2.0      183.0
26712  26713      05/19/2020       Zhejiang  ...    1268.0    1.0     1267.0

[26713 rows x 8 columns]

In [ ]:
df.drop(columns = ['SNo','Last Update'],inplace = True)

In [ ]:
df

ObservationDate Province/State  ... Deaths  Recovered
0          01/22/2020          Anhui  ...    0.0        0.0
1          01/22/2020        Beijing  ...    0.0        0.0
2          01/22/2020      Chongqing  ...    0.0        0.0
3          01/22/2020         Fujian  ...    0.0        0.0
4          01/22/2020          Gansu  ...    0.0        0.0
...               ...            ...  ...    ...        ...
26708      05/19/2020        Wyoming  ...   10.0        0.0
26709      05/19/2020       Xinjiang  ...    3.0       73.0
26710      05/19/2020          Yukon  ...    0.0       11.0
26711      05/19/2020         Yunnan  ...    2.0      183.0
26712      05/19/2020       Zhejiang  ...    1.0     1267.0

[26713 rows x 6 columns]

In [ ]:
df.rename(columns = {"Province/State":"State","Country/Region":"Country"},inplace = True)

In [ ]:
df

ObservationDate      State         Country  Confirmed  Deaths  Recovered
0          01/22/2020      Anhui  Mainland China        1.0     0.0        0.0
1          01/22/2020    Beijing  Mainland China       14.0     0.0        0.0
2          01/22/2020  Chongqing  Mainland China        6.0     0.0        0.0
3          01/22/2020     Fujian  Mainland China        1.0     0.0        0.0
4          01/22/2020      Gansu  Mainland China        0.0     0.0        0.0
...               ...        ...             ...        ...     ...        ...
26708      05/19/2020    Wyoming              US      776.0    10.0        0.0
26709      05/19/2020   Xinjiang  Mainland China       76.0     3.0       73.0
26710      05/19/2020      Yukon          Canada       11.0     0.0       11.0
26711      05/19/2020     Yunnan  Mainland China      185.0     2.0      183.0
26712      05/19/2020   Zhejiang  Mainland China     1268.0     1.0     1267.0

[26713 rows x 6 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26713 entries, 0 to 26712
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   ObservationDate  26713 non-null  object 
 1   State            12882 non-null  object 
 2   Country          26713 non-null  object 
 3   Confirmed        26713 non-null  float64
 4   Deaths           26713 non-null  float64
 5   Recovered        26713 non-null  float64
dtypes: float64(3), object(3)
memory usage: 1.2+ MB


In [ ]:
df['ObservationDate'] = pd.to_datetime(df['ObservationDate'])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26713 entries, 0 to 26712
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype         
---  ------           --------------  -----         
 0   ObservationDate  26713 non-null  datetime64[ns]
 1   State            12882 non-null  object        
 2   Country          26713 non-null  object        
 3   Confirmed        26713 non-null  float64       
 4   Deaths           26713 non-null  float64       
 5   Recovered        26713 non-null  float64       
dtypes: datetime64[ns](1), float64(3), object(2)
memory usage: 1.2+ MB


In [ ]:
df.head()

ObservationDate      State         Country  Confirmed  Deaths  Recovered
0      2020-01-22      Anhui  Mainland China        1.0     0.0        0.0
1      2020-01-22    Beijing  Mainland China       14.0     0.0        0.0
2      2020-01-22  Chongqing  Mainland China        6.0     0.0        0.0
3      2020-01-22     Fujian  Mainland China        1.0     0.0        0.0
4      2020-01-22      Gansu  Mainland China        0.0     0.0        0.0

In [ ]:
max = df['Confirmed'].max()

In [ ]:
df[df['Confirmed']==max]

ObservationDate     State Country  Confirmed   Deaths  Recovered
26638      2020-05-19  New York      US   352845.0  28558.0        0.0

          confirmed deaths recovered
country -> 

In [ ]:
df_new=df.groupby(df['Country']).sum()

In [ ]:
df

ObservationDate      State         Country  Confirmed  Deaths  Recovered
0          2020-01-22      Anhui  Mainland China        1.0     0.0        0.0
1          2020-01-22    Beijing  Mainland China       14.0     0.0        0.0
2          2020-01-22  Chongqing  Mainland China        6.0     0.0        0.0
3          2020-01-22     Fujian  Mainland China        1.0     0.0        0.0
4          2020-01-22      Gansu  Mainland China        0.0     0.0        0.0
...               ...        ...             ...        ...     ...        ...
26708      2020-05-19    Wyoming              US      776.0    10.0        0.0
26709      2020-05-19   Xinjiang  Mainland China       76.0     3.0       73.0
26710      2020-05-19      Yukon          Canada       11.0     0.0       11.0
26711      2020-05-19     Yunnan  Mainland China      185.0     2.0      183.0
26712      2020-05-19   Zhejiang  Mainland China     1268.0     1.0     1267.0

[26713 rows x 6 columns]

In [ ]:
df_new.reset_index()

Country  Confirmed   Deaths  Recovered
0                        Azerbaijan        1.0      0.0        0.0
1                   ('St. Martin',)        2.0      0.0        0.0
2                       Afghanistan   115615.0   3211.0    13641.0
3                           Albania    34319.0   1408.0    20212.0
4                           Algeria   183263.0  19089.0    76184.0
..                              ...        ...      ...        ...
218                  Western Sahara      256.0      0.0      144.0
219                           Yemen     1190.0    190.0       30.0
220                          Zambia     8987.0    166.0     3102.0
221                        Zimbabwe     1386.0    171.0      226.0
222  occupied Palestinian territory       25.0      0.0        0.0

[223 rows x 4 columns]